<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="footer-style-16">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-16-content')->toHtml(); ?>

    <div class="footer-bottom">
        <div class="container">
            <div class="bt-content clearfix">
                <div class="add-footer">
                    <?php if ($_config->getAdvanced('copyright_group/custom_copyright')) { ?>
                        <address><?php echo $_config->getAdvanced('copyright_group/copyright_content') ?></address>
                    <?php } else { ?>
                        <address><?php echo $this->getChildHtml("copyright"); ?></address>
                    <?php } ?>
                </div>

                <div class="news-socials">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-socials')->toHtml(); ?>
                </div>

            </div>
        </div>
    </div>
</div>