<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="footer-style-19">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-19-content')->toHtml(); ?>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="social-footer">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social-block')->toHtml(); ?>
                    </div>
                </div>

                <div class="col-lg-6">
                    <?php if ($_config->getAdvanced('copyright_group/custom_copyright')) { ?>
                        <address><?php echo $_config->getAdvanced('copyright_group/copyright_content') ?></address>
                    <?php } else { ?>
                        <address><?php echo $this->getChildHtml("copyright"); ?></address>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>