<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="footer-style-17">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-17-content')->toHtml(); ?>

    <div class="footer-bottom">
        <div class="container">
            <div class="ft-bottom-content">
                <div class="footer-links-bottom">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links-bottom')->toHtml(); ?>
                </div>

                <div class="footer-copyright">
                    <?php if ($_config->getAdvanced('copyright_group/custom_copyright')) { ?>
                        <address><?php echo $_config->getAdvanced('copyright_group/copyright_content') ?></address>
                    <?php } else { ?>
                        <address><?php echo $this->getChildHtml("copyright"); ?></address>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>