<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="footer-style-26">
   
	<div class="footer-top">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-26-content')->toHtml(); ?>
	
	</div>
	
    <div class="footer-bottom">
        <div class="container">
			<div class="row">
				
                <div class="col-lg-12">
                    
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer-34')->toHtml(); ?> 
					<?php if ($_config->getAdvanced('copyright_group/custom_copyright')) { ?>
                        <address><?php echo $_config->getAdvanced('copyright_group/copyright_content') ?></address>
                    <?php } else { ?>
                        <address><?php echo $this->getChildHtml("copyright"); ?></address>
                    <?php } ?>
                </div>

                
            </div>
			
            

        </div>
    </div>
</div>