<?php
/*------------------------------------------------------------------------
# SM Categories - Version 3.2.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getList();
?>

<div class="block block-categories">
    <div class="block-title">
        <strong><?php echo __($this->_getConfig('title_module')); ?></strong>
    </div>

    <div class="block-content">
        <?php if (!empty($list)) { ?>
            <div class="cat-wrap ">
                <div class="owl-carousel owl-theme">
                    <?php foreach ($list as $item) { ?>
                        <div class="item">
                            <div class="content-box">
                                <div class="cats-info">
                                    <h2 class="cat-title">
                                        <a href="<?php echo $item['url'] ?>" title="<?php echo $item['name'] ?>">
                                            <?php echo __($item['name']); ?>
                                        </a>
                                    </h2>

                                    <div class="child-cat">
                                        <ul class="sub-cats">
                                            <?php
                                            if (isset($item['children_info']) && !empty($item['children_info'])) {
                                                $children_cats = $item['children_info'];
                                                foreach ($children_cats as $children) { ?>
                                                    <li class="child-title">
                                                        <a href="<?php echo $children['url'] ?>"
                                                           title="<?php echo __($children['name']) ?>">
                                                            <?php echo __($children['name']); ?>
                                                            <span class="count">(<?php echo $children['product_count']; ?>)</span>
                                                        </a>
                                                    </li>
                                                    <?php
                                                }
                                            } ?>
                                        </ul>

                                        <a class="btn-view" href="<?php echo $item['url'] ?>"
                                           title="<?php echo $item['name'] ?>">
                                            <?php echo __('View all'); ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        <?php } else { ?>
            <div class="message info empty">
                <div><?php /* @escapeNotVerified */
                    echo __('We can\'t find categories matching the selection.') ?></div>
            </div>
        <?php } ?>
    </div>
</div>


