<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$_config         = $this->helper('Sm\BundleImage\Helper\Data');
$mediaSrc        = $_config->getMediaUrl();
$noSelectedImage = $_config->getGeneral('no_select_image');

if ($noSelectedImage) {
    $noSelectedImageSrc = $mediaSrc . "sm_bundle/" . $noSelectedImage;
} else {
    $noSelectedImageSrc = $mediaSrc . "sm_bundle/not-selected.jpg";
}
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required' : '' ?>">
    <label class="label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()) : ?>
            <?= /* @noEscape */
            $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"
                   class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?> bundle option"/>
        <?php else : ?>
            <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][]"
                    data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][]"
                    class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?> multiselect product bundle option change-container-classname"
                <?php if ($_option->getRequired()) {
                    echo 'data-validate={required:true}';
                } ?>>
                <?php if (!$_option->getRequired()) : ?>
                    <option value=""><?= $block->escapeHtml(__('None')) ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection) : ?>
                    <?php
                    $productLink = $block->getProductLink($_selection);
                    ?>
                    <option value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            data-image="<?= /* @noEscape */
                            $block->getProductImage($_selection) ?>"

                        <?php if ($productLink) { ?>
                            data-url="<?php echo $productLink; ?>"

                            <?php if ($_config->checkQuickView()) { ?>
                                data-quickview-url="<?php echo $this->getUrl('') . "cartquickpro/catalog_product/view/id/" . $_selection->getId() ?>"
                            <?php } ?>
                        <?php } ?>
                        <?php if ($block->isSelected($_selection)) {
                            echo ' selected="selected"';
                        } ?>
                        <?php if (!$_selection->isSaleable()) {
                            echo ' disabled="disabled"';
                        } ?>>
                        <?= /* @noEscape */
                        $block->getSelectionQtyTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>

            <div class="child-bundle-items">
                <div class="item no-select">
                    <a class="bundle-image" href="javascript:void(0)" target="_blank">
                        <img src="<?php echo $noSelectedImageSrc; ?>" width="90" height="90"/>
                    </a>

                    <?php if ($_config->checkQuickView()) { ?>
                        <a class="bundle-quickview"
                           href="javascript:void(0)">
                            <?php echo $_config->getQuickCartConfig('label_button') ?>
                        </a>
                    <?php } ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
