/**
* Home page
*/

.slidershow-type-1 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.top-home-search ul li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.hot-categories .block-title strong{
border-bottom: 2px solid #<?php echo $themeColor; ?>;
}

.hot-categories .cat-title a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.home-collection .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.home-collection .item a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.tabs-product .sm-listing-tabs .ltabs-wrap .ltabs-tabs-container .ltabs-tabs li:hover,
.tabs-product .sm-listing-tabs .ltabs-wrap .ltabs-tabs-container .ltabs-tabs li.tab-sel{
border-color: #<?php echo $themeColor; ?>!important;
color: #<?php echo $themeColor; ?>;
}

.sidebar-home .block-clients .owl-theme .owl-nav [class*='owl-']:hover,
.tabs-product .owl-theme .owl-nav [class*='owl-']:hover,
.home-collection .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-subscribe-home .action-button button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.content-home .vertical-menu-content:before{
background-color: #<?php echo $themeColor; ?>;
}


.content-home .sm_megamenu_wrapper_vertical_menu ul.sm_megamenu_menu>li:hover > a{
color: #<?php echo $themeColor; ?>;
}

.content-home .sm_megamenu_wrapper_vertical_menu ul.sm_megamenu_menu>li > a:before{
background-color: #<?php echo $themeColor; ?>;
}

.content-home .more-w .more-view:hover{
color: #<?php echo $themeColor; ?>;
}

.content-home .vertical-menu-block .vertical-menu-content .navigation > ul > li > a:before{
background-color: #<?php echo $themeColor; ?>;
}

.content-home .vertical-menu-block .vertical-menu-content .navigation > ul > li.active > a,
.content-home .vertical-menu-block .vertical-menu-content .navigation > ul > li.has-active > a,
.content-home .vertical-menu-block .vertical-menu-content .navigation > ul > li:hover > a{
color: #<?php echo $themeColor; ?>;
}

.product-top-home .deals-countdown{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.collection-sidebar ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.line-slider .owl-theme .owl-nav [class*='owl-']:hover,
.deal-slider .owl-theme .owl-nav [class*='owl-']:hover,
.brand-slider .owl-theme .owl-nav [class*='owl-']:hover,
.blog-slider .owl-theme .owl-nav [class*='owl-']:hover,
.products-list-slider .owl-theme .owl-nav [class*='owl-']:hover,
.hot-categories.categories-slider .owl-theme .owl-nav [class*='owl-']:hover,
.blog-slider .post-read-more a:hover,
.deal-slider .product-item-actions .actions-secondary .action:hover,
.deal-slider .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-slider .deals-countdown{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.client-slider .client-text,
.deal-slider .product-item-info:hover .image-product .quickview-handler:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.client-slider .owl-theme .owl-dots .owl-dot.active span,
.client-slider .owl-theme .owl-dots .owl-dot:hover span{
background-color: #<?php echo $themeColor; ?>;
}

.home-services.service-grid > ul > li > a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.home-collection.collection-grid .item a{
border-bottom: 2px solid #<?php echo $themeColor; ?>;
}

.tab-grid .sm-listing-tabs .ltabs-wrap .ltabs-tabs-container .ltabs-tabs li.tab-sel,
.tab-grid .sm-listing-tabs .ltabs-wrap .ltabs-tabs-container .ltabs-tabs li:hover{
border-top-color: #<?php echo $themeColor; ?>;
color: #<?php echo $themeColor; ?>;
}

.tab-grid .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.brand-grid .item:hover{
border-color: #<?php echo $themeColor; ?>;
}

.brand-grid .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.list-product-buttons .product-item-actions .actions-secondary .action:hover,
.list-product-buttons .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.tabs-style-2.tab-hot .thumbs-product .item-img.thumb-active{
border-color: #<?php echo $themeColor; ?>;
}

.home-bottom-content .bottom-newsletter .subscribe-home .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.home-bottom-content .bottom-newsletter .subscribe-home .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.brand-inner .owl-theme .owl-nav [class*='owl-']:hover,
.simple-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.tab-hot-center .thumbs-product .item-img.thumb-active{
border-color: #<?php echo $themeColor; ?>;
}

.cats-list .cat-info > a{
color: #<?php echo $themeColor; ?>;
}

.blog-slider-type-2 .date-post{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.blog-slider-type-2 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-banner-slider .owl-theme .owl-dots .owl-dot.active span{
background-color: #<?php echo $themeColor; ?>;
}

.full-banner-slider .item .banner-info > a{
color: #<?php echo $themeColor; ?>;
}

.top-service ul li a:after{
background-color: #<?php echo $themeColor; ?>;
}

.block-box .block-box-title strong{
color: #<?php echo $themeColor; ?>;
}

.block-box .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?> !important;
border-color: #<?php echo $themeColor; ?> !important;
color: #<?php echo $textOnThemeColor; ?> !important;
}

.blog-slider-type-3 .date-post{
background-color: #<?php echo $themeColor; ?> !important;
color: #<?php echo $textOnThemeColor; ?> !important;
}

.newsletter-bottom-home .action-button button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-countdown .deals-countdown .deals-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-countdown .product-item-actions .actions-primary button:hover,
.deal-countdown .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-countdown .product-item-info .image-product .quickview-handler:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-countdown .owl-theme .owl-dots .owl-dot.active span,
.deal-countdown .owl-theme .owl-dots .owl-dot:hover span{
background-color: #<?php echo $themeColor; ?>;
}

.slidershow-type-3 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-home .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?> !important;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-slider-cats .info-cat a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.slider-product-list .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-box .deals-countdown .deals-time{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-box .product-item-actions .actions-primary button:hover,
.deal-box .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-box .product-item-info .image-product .quickview-handler:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-grid-cats .block-categories .cat-wrap .item .cat-title a:hover{
color: #<?php echo $themeColor; ?>;
}

.block-deals-full .deals-countdown .deals-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.slidershow-type-6 .owl-theme .owl-nav [class*='owl-']:hover,
.slidershow-type-5 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-big-cats .block-categories .cat-wrap .item .image-cat a:before{
background-color: #<?php echo $themeColor; ?>;
}

.block-dot-title .block .block-title strong{
color: #<?php echo $themeColor; ?>;
}

.dot-brands ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.deal-syns-container{
border: 2px solid #<?php echo $themeColor; ?>;
}

.deal-syns-container .thumb-deal .thumb-item:hover,
.deal-syns-container .thumb-deal .thumb-item.active{
border-color: #<?php echo $themeColor; ?>;
}

.deal-syns-container .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-syns-container .deals-countdown .deals-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.slidershow-type-7 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-top-des .block-title p{
color: #<?php echo $themeColor; ?>;
}

.block-top-des .owl-theme .owl-dots .owl-dot:hover span,
.block-top-des .owl-theme .owl-dots .owl-dot.active span{
background-color: #<?php echo $themeColor; ?>;
}

.block-top-des .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.slidershow-type-8 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-services .service-banner .button-play a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.list-brand-items ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.block-cat-22 .block-categories .cat-wrap .item .cat-title a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.blog-22 .post-read-more a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-deals-product .block-content-products .product-item-details .deals-countdown{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-deals-product .block-content-products .box-image-deal .quickview-handler:hover,
.full-deals-product .bottom-action form button:hover,
.full-deals-product .bottom-action .tocompare:hover,
.full-deals-product .bottom-action .towishlist:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-deals-product .thumb-product .box-image-thumb.active-item{
border-color: #<?php echo $themeColor; ?>;
}

.title-2 .block .block-title:before{
background-color: #<?php echo $themeColor; ?>;
}

.nav-text .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.cat-slider .cat-title a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.sv-list .sv-item a:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deals-count .deals-countdown .deals-time .num-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-8-style .deals-count .products-grid .product-item-info .product-item-actions .actions-secondary .action:hover,
.product-8-style .deals-count .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.attr-container .smas-container .chosen-container-single .chosen-single div{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.attr-container .smas-container .smas-attr-inner button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.attr-container .smas-container .smas-attr-inner button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.cats-grid-inner .content-box:hover .cats-info a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-des-bottom .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.bottom-grid-brand ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.slidershow-type-9 .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.content-box-cat .cat-title a{
border-bottom: 2px solid #<?php echo $themeColor; ?>;
}

.content-box-cat:hover .cat-title a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.content-box-cat .child-cat a:hover,
.content-box-cat .child-cat .btn-view{
color: #<?php echo $themeColor; ?>;
}

.tabs-product-banner .owl-theme .owl-nav [class*='owl-']:hover,
.slider-product-filter .owl-theme .owl-nav [class*='owl-']:hover,
.content-client-icon .owl-theme .owl-nav [class*='owl-']:hover,
.content-brand-icon .owl-theme .owl-nav [class*='owl-']:hover,
.block-categories-inner .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.content-brand-icon .item a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.content-client-icon .cl-say:before{
color: #<?php echo $themeColor; ?>;
}

.content-client-icon .item-client:hover .cl-info{
background-color: #<?php echo $themeColor; ?>;
}

.content-client-icon .item-client:hover .cl-info .cl-name,
.content-client-icon .item-client:hover .cl-info .cl-country{
color: #<?php echo $textOnThemeColor; ?>;
}

.product-10-style .slider-product-filter .deals-countdown .deals-time .num-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.tabs-product-banner .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel,
.tabs-product-banner .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:hover{
color: #<?php echo $themeColor; ?>;
}

.client-farm .social-f a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.f-service-full{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.f-service-full a{
color: #<?php echo $textOnThemeColor; ?>;
}

.f-clients .cl-des:after{
color: #<?php echo $themeColor; ?>;
}

.f-brands .item:hover{
border-color: #<?php echo $themeColor; ?>;
}

.f-brands .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.f-brands .owl-theme .owl-dots .owl-dot:hover span,
.f-brands .owl-theme .owl-dots .owl-dot.active span{
background-color: #<?php echo $themeColor; ?>;
}

.med-brand .item a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.med-brand .owl-theme .owl-nav [class*='owl-']:hover{
color: #<?php echo $themeColor; ?>;
}

.list-crub .crub-button a{
color: #<?php echo $themeColor; ?>;
}

.list-crub .crub-button a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.med-client .text{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.med-client .text:before{
border-top: 25px solid #<?php echo $themeColor; ?>;
}

.med-product .product-item-details .deals-countdown .num-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.med-l-product .products-grid .product-item-actions .actions-primary .action:hover{
background-color: #<?php echo $themeColor; ?> !important;
color: #<?php echo $textOnThemeColor; ?> !important;
}

.med-l-product .block-title a{
color: #<?php echo $themeColor; ?>;
}

.banner-des .btn-shop a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.service-min > ul > li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.subcribe-home-min .action-button button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.tabs-product-flex .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel{
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $themeColor; ?>;
}

.tabs-product-flex .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:hover{
color: #<?php echo $themeColor; ?>;
}

.row-brand-slider .item a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.grid-cats a:hover span{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.b-client-full .b-client-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.attr-container.attr-b .smas-container .chosen-container-single.chosen-disabled .chosen-single div{
color: #<?php echo $themeColor; ?>;
}

.gallery-img-b .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-b .ver-title{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-b .bottom-action form button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-b .bottom-action form button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.deal-b .bottom-action .tocompare:hover,
.deal-b .bottom-action .towishlist:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.deal-b .box-image-deal .quickview-handler:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}
.gallery-img .block-content a:hover{
	border-color: #<?php echo $themeColor; ?>; 
}

.block-home-30 .owl-theme .owl-nav [class*='owl-']:hover{ 
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
border-color: #<?php echo $themeColor; ?>;  
}
.fashion-categories > .container .cat-wrap .item .content-box:hover .cats-info h2 a{
	color: #<?php echo $themeColor; ?>;  
}
.block-home-31.banner-home .item .content a.view-more:hover {
	background-color: #<?php echo $themeColorDarken ; ?>;
}
.banner-room .item .content a.shop-now:hover {
	background-color: #<?php echo $themeColor; ?>;
}
.blog-home-31 .block-slider-post .item .info-post .post-title a:hover {
	color: #<?php echo $themeColor; ?>;
}
.block-home-31 .flipdown.flipdown__theme-dark .rotor-bottom, 
.block-home-31 .flipdown.flipdown__theme-dark .rotor-leaf-rear{ 
	background-color: #<?php echo $themeColorDarken; ?>; 
	color: #<?php echo $textOnThemeColor; ?>;
}
.block-home-31 .flipdown.flipdown__theme-dark .rotor, 
.block-home-31 .flipdown.flipdown__theme-dark .rotor-top,
.block-home-31  .flipdown.flipdown__theme-dark .rotor-leaf-front{
 	background-color: #<?php echo $themeColor; ?>; 
	color: #<?php echo $textOnThemeColor; ?>;
 }
.block-home-31 .flipdown .rotor:after{
 	border-color: #<?php echo $themeColor; ?>;
 }
 .block-deal-full-31 .block-filterproducts .products-grid .product-item-info .product-item-details .price-box .price{
	 color: #<?php echo $themeColor; ?>;
 }
.block-deal-full-31 .block-filterproducts .products-grid .product-item-info .product-item-details .product-item-name a:hover {
	color: #<?php echo $themeColor; ?>;
}
.block-deal-full-31 .block-filterproducts .products-grid .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,
.block-deal-full-31 .block-filterproducts .products-grid .product-item-info .product-item-details .product-item-actions .actions-primary button:hover {
	background-color: #<?php echo $themeColor; ?> !important; 
	color: #<?php echo $textOnThemeColor; ?> !important; 
 }
 .block-home-31 .block-categories .cat-wrap .item:hover .cat-title a{
	 color: #<?php echo $themeColor; ?>;
 }
 .listingtab-style.block-home-32 .ltabs-wrap .ltabs-tabs-container .ltabs-tab.tab-sel .ltabs-tab-img, 
 .listingtab-style.block-home-32 .ltabs-wrap .ltabs-tabs-container .ltabs-tab:hover .ltabs-tab-img{
	 background-color: #<?php echo $themeColor; ?> !important; 
 }
.block-categories-slider.block-home-32 .block-categories .cat-wrap .item:hover .cats-info h2.cat-title{
	background-color: #<?php echo $themeColor; ?> !important; 
	
}
.block-categories-slider.block-home-32 .block-categories .cat-wrap .item:hover .cats-info h2.cat-title a{
	color: #<?php echo $textOnThemeColor; ?> !important; 
}
.block-home-32 .owl-theme .owl-nav [class*='owl-']:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;  
}
.block-home-32.blog-home-32 .block-slider-post .item .info-post .date-post{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.block-home-32.blog-home-32 .block-slider-post .item:hover .info-post .post-title a:hover,
.block-home-32.blog-home-32 .block-slider-post .item:hover .info-post .post-read-more a:hover{
	color: #<?php echo $themeColor; ?>;
}
.block-home-32.block-service .item:hover:before{
	border-color: #<?php echo $themeColor; ?>;  
}
.block-home-32 .owl-theme .owl-dots .owl-dot.active span, 
.block-home-32 .owl-theme .owl-dots .owl-dot:hover span{ 
	background-color: #<?php echo $themeColor; ?>;
}
.listingtab-style.block-home-32 .ltabs-wrap .ltabs-tabs-container .ltabs-tab.tab-sel .ltabs-tab-label, 
.listingtab-style.block-home-32 .ltabs-wrap .ltabs-tabs-container .ltabs-tab:hover .ltabs-tab-label{
	color: #<?php echo $themeColor; ?>;
}
.block-home-33.block-deal-products .block-filterproducts .title-countdown-slider,
.block-home-33 .btn-viewmore a:hover,
.block-group-hot .block-item.block-popular .block-filterproducts .owl-theme .owl-nav [class*="owl-"]:hover,
.block-home-33.block-sale-off .btn-shopnow:hover{
	background-color: #<?php echo $themeColor; ?>;
}
.block-home-33 .block-categories .cat-wrap .item .btn-view,
.block-home-33 .block-categories .cat-wrap .item:hover .cat-title a,
.block-home-33.banner-home .content .item:hover strong{
	color: #<?php echo $themeColor; ?>;
}
.block-home-33 .owl-theme .owl-nav [class*='owl-']:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.fashion-categories-v35 .block-categories .cat-wrap .item:hover .cats-info a.btn-view,
.block-aboutus-35 .content a.bt-shop:hover{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.block-customer.block-home-35 .block-content .item:hover .img-customer:before {
	border-color: #<?php echo $themeColor; ?>;
}
.block-customer.block-home-35 .block-content .item:hover h3.name{
	color: #<?php echo $themeColor; ?>;
}
.block-home-35 .owl-theme .owl-nav [class*=owl-]:hover {
	color: #<?php echo $themeColor; ?> !important;
}
.slidershow-type-36 .owl-theme .owl-nav [class*=owl-]:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.home-page-36 .block-promotions .block-content .item:hover span{
	color: #<?php echo $themeColor; ?>;
}
.home-page-36 .deal-progress-bar {
	background-color: #<?php echo $themeColor; ?>;
}

.block-home-37 .flipdown.flipdown__theme-dark .rotor-bottom, 
.block-home-37 .flipdown.flipdown__theme-dark .rotor-leaf-rear,
.block-home-37.block-deal-full-37 .view-more:hover{ 
	background-color: #<?php echo $themeColor; ?>; 
	color: #<?php echo $textOnThemeColor; ?>;
}
.block-home-37 .flipdown.flipdown__theme-dark .rotor, 
.block-home-37 .flipdown.flipdown__theme-dark .rotor-top,
.block-home-37  .flipdown.flipdown__theme-dark .rotor-leaf-front, 
.client-farmer.block-home-37 .item:hover  .info-f ul.social-f li a{
 	background-color: #<?php echo $themeColorDarken; ?>; 
	color: #<?php echo $textOnThemeColor; ?>;
 }
.block-home-37 .flipdown .rotor:after,
.client-farmer.block-home-37 .item:hover {
 	border-color: #<?php echo $themeColor; ?>;
 }
 .block-home-37 .owl-theme .owl-nav [class*='owl-']:hover {
	background-color: #<?php echo $themeColor; ?>; 
	color: #<?php echo $textOnThemeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;
	 
 }
.block-home-37.block-categories-v37 .item:hover span{
	color: #<?php echo $themeColor; ?>;	 
}
.slidershow-type-38 .owl-theme .owl-nav [class*=owl-]:hover ,
.block-home-38 .owl-theme .owl-nav [class*='owl-']:hover{
	background-color: #<?php echo $themeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>; 
}
.fashion-categories-38 .block-categories .cat-wrap .item:hover .cats-info h2 a,
.policy-shop-v38 .item:hover .info h5 a{
	color: #<?php echo $themeColor; ?>;
}
.block-clientsay38 .item:hover .client-info{
	background-color: #<?php echo $themeColor; ?>;
}
.deal-syns-container-v38{
	border-color: #<?php echo $themeColor; ?>;
}
.listingtab-v38 .thumbs-product .item-img.thumb-active,
.listingtab-v38 .thumbs-product .item-img:hover {
	border-color: #<?php echo $themeColor; ?>;   
}
.listingtab-v38 .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel:before{
	background-color: #<?php echo $themeColor; ?>;
}
.deal-syns-container-v38 .thumb-product .box-image-thumb.active-item,
.deal-syns-container-v38 .thumb-product .box-image-thumb:hover{
	border-color: #<?php echo $themeColor; ?>; 
}
.deal-syns-container-v38 .deals-countdown .deals-time{
	background-color: #<?php echo $themeColor; ?>;
}
.deal-syns-container-v38 .actions-secondary .action:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>; 
}
.block-home-39 .owl-theme .owl-nav [class*='owl-']:hover:before{
	color: #<?php echo $themeColor; ?>;
}
.slidershow-type-39 .owl-theme .owl-nav [class*='owl-']:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>; 
}
.block-home-39.blog-slider-type-6 .item .date-post{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>; 
}
.filterProducts-scroll .block.block-filterproducts .title-deals,
.block-home-39.block-banner-video .button-wrap > a:hover,
.block-wrapper-video-banner .banner-images .button-play a.play-video:hover,
.newsletter-testimonial .block-home-39.newsletter-home {
	background-color: #<?php echo $themeColor; ?>; 
	color: #<?php echo $textOnThemeColor; ?>; 
}
.filterProducts-scroll .block.block-filterproducts .title-deals .block-title{
	background-color: #<?php echo $themeColorDarken; ?>; 
}
