/**
* Footer 1
*/

.footer-style-1 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-1 .newsletter-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-1 .newsletter-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.footer-style-1 .footer-bottom address a{
color: #<?php echo $themeColor; ?>;
}

/**
* Footer 2
*/

.footer-style-2 .newsletter-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-2 .footer-bottom a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-2 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 3
*/

.footer-style-3 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-3 .footer-block .links-footer li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

/**
* Footer 4
*/

.footer-style-4 .newsletter-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-4 .newsletter-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.footer-style-4 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 5
*/

.footer-style-5 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 6
*/

.footer-style-6 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 7
*/

.footer-style-7 .footer-bottom{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-7 .footer-bottom a{
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-7 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 8
*/

.footer-style-8 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-8 .block-subscribe-footer .action-button button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 9
*/

.footer-style-9 .footer-block .footer-block-title:before{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-9 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-9 .newsletter-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-9 .newsletter-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Footer 10
*/

.footer-style-10 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-10 .block-subscribe-footer .action-button button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 11
*/

.footer-style-11 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 12
*/

.footer-style-12 .footer-head{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-12 .footer-head .newsletter-title{
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-12 .block-subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-12 .footer-block .footer-block-title:before{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-12 .footer-description .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 13
*/

.footer-style-13 .footer-head .newsletter-title .news-bottom{
color: #<?php echo $themeColor; ?>;
}

.footer-style-13 .block-subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-13 .footer-block .footer-block-title:before{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-13 .footer-cat-social .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-13 .footer-block.footer-contact .contact-info li:before{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 14
*/

.footer-style-14 .ft-bottom-content .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 15
*/

.footer-style-15 .ft-bottom-content .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-15 .menu-footer li a:hover{
color: #<?php echo $themeColor; ?>;
}

/**
* Footer 16
*/

.footer-style-16 .sv-footer-item .sv-info strong{
color: #<?php echo $themeColor; ?>;
}

.footer-style-16 .footer-middle .links-footer ul li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.footer-style-16 .footer-bottom .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 17
*/
.footer-style-17 .footer-phone a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-17 .block-subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-17 .social-footer .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 18
*/

.footer-style-18 .ft-newsletter{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-18 .ft-newsletter .title-newsletter{
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-18 .footer-block .contact-footer li:before{
color: #<?php echo $themeColor; ?>;
}

.footer-style-18 .footer-block .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 19
*/

.footer-style-19 .subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-19 .subscribe-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.footer-style-19 .middle-top .footer-links a:hover{
color: #<?php echo $themeColor; ?>;
}

.footer-style-19 .middle-bottom .btn-map a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-19 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 21
*/
.menu-footer li a:hover{
color: #<?php echo $themeColor; ?>;
}

.footer-style-21 .ft-bottom-content .social-block-list ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-21 .block-subscribe-footer .action-button button:hover{
color: #<?php echo $themeColor; ?> !important;
}
/**
* Footer 24
*/
.footer-style-24 .before-footer .content .social-footer ul li a:hover {
	background-color: #<?php echo $themeColor; ?>;
}
.footer-style-24 .footer-block .footer-block-content ul li a:hover, 
.footer-style-24 .page-footer a,
.footer-style-24 .block-subscribe-footer .action-button button:before,
.footer-style-24 .hotline-shop strong {

	color: #<?php echo $themeColor; ?>;
}
/**
* Footer 25
*/
.footer-style-25 .footer-block ul li a:hover,
.footer-style-25 .footer-service .item:hover .info h3{ 
	color: #<?php echo $themeColor; ?>;
}
.footer-style-25 .social-block-list ul li a:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.footer-style-25 .block-subscribe-footer .action-button button:hover{
	background-color: #<?php echo $themeColor; ?>;
}
/**
* Footer 26
*/
.footer-style-26 .footer-block ul li a:hover{
	color: #<?php echo $themeColor; ?>;
}
.footer-style-26  .social-block-list ul li a:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.footer-style-26 .block-subscribe-footer .action-button button:hover {
	background-color: #<?php echo $themeColor; ?> !important; 
	border-color: #<?php echo $themeColor; ?> !important; 
}
.footer-style-27 .block-subscribe-footer .action-button button:hover {
	background-color: #<?php echo $themeColor; ?> !important;
	border-color: #<?php echo $themeColor; ?> !important;
}
/**
* Footer 28
*/
.footer-style-28 .block-subscribe-footer .action-button button:hover {
	background-color: #<?php echo $themeColor; ?> !important;
	border-color: #<?php echo $themeColor; ?> !important;
}
/**
* Footer 29
*/
.footer-style-29 .block-subscribe-footer .newsletter-content button{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-29 .footer-bottom ul li a:hover,.footer-style-29 .footer-bottom address a:hover {
	color: #<?php echo $themeColor; ?> !important;	
}
/**
* Footer 30
*/

.footer-style-30 .footer-block .ft-links a:hover {
	color: #<?php echo $themeColor; ?> !important;	
}
.footer-style-30 .footer-top {
	background-color: #<?php echo $themeColor; ?>;
}
.footer-style-30 .block-subscribe-footer .newsletter-content button:hover {
	color: #<?php echo $themeColor; ?>;
}
/**
* Footer 31
*/
.footer-31-style .block-subscribe-footer .action-button button{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.footer-31-style .social-block-list ul li a:hover {
	color: #<?php echo $themeColor; ?>;
}
.footer-31-style .block-subscribe-footer .action-button button:hover{
	background-color: #<?php echo $themeColorDarken; ?>; 
}