<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_config         = $this->helper('Sm\Themecore\Helper\Data');
$tabStyle        = $_config->getProductDetail('tabs_group/tab_style');
$show_custom_tab = $_config->getProductDetail('tabs_group/show_custom_tab');
$custom_tab_name = $_config->getProductDetail('tabs_group/custom_tab_name');
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product-info-detailed">
        <div class="container">
            <?php $layout = $block->getLayout(); ?>
            <div class="product-data-items">
                <ul class="list-tab-sticky">
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <li class="data item title">
                            <a class="data switch"
                               href="javascript:void(0);"
                               data-tabcontent="tab-label-<?= /* @escapeNotVerified */
                               $alias ?>">
                                <?= /* @escapeNotVerified */
                                $label ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                    <?php if ($show_custom_tab) { ?>
                        <li class="data item title">
                            <a class="data switch"
                               href="javascript:void(0);"
                               data-tabcontent="tab-label-customtab">
                                <?php echo $custom_tab_name ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            var heightSticky;

            <?php if ($_config->getProductDetail('sticky_addtocart_tabs/position_bottom') && $_config->getGeneral('navigation_group/menu_ontop')) {?>
            heightSticky = $(".ontop-element").height() + 20;
            <?php } else if($_config->getProductDetail('sticky_addtocart_tabs/position_bottom') && !$_config->getGeneral('navigation_group/menu_ontop')){?>
            heightSticky = 20;
            <?php } else {?>
            heightSticky = $(".sticky-product-action").height() + 20;
            <?php } ?>

            var tabOffsetTop;
            var tabOffset;

            $(".product-data-items .data.switch").click(function () {
                var dataTab = $(this).attr("data-tabcontent");

                <?php if($tabStyle == "vertical"){?>
                tabOffsetTop = $(".product.info.detailed").offset().top;
                <?php } else {?>
                tabOffsetTop = $("#" + dataTab).offset().top;
                <?php }?>

                tabOffset = tabOffsetTop - heightSticky;
                $(".product-data-items .data.switch").removeClass("active");
                $(this).addClass("active");
                $("html, body").animate({scrollTop: tabOffset}, 200);

                setTimeout(function () {
                    $("#" + dataTab).trigger("click");
                }, 200);

            });

        });
    </script>
<?php endif; ?>
