<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.3.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Themecore\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode        = 'grid';
    $image           = 'category_page_grid_big';
    $showDescription = false;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist    = true;
    $showCompare     = true;
    $showCart        = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = 0;
if ($block->getPositioned()) {
    $pos = $block->getPositioned();
};
    $tag_id = "filter-products-" . rand();
    ?>
    <div class="block block-filterproducts">
        <?php if (!empty($this->_getConfig('title_module'))) { ?>
            <div class="block-title">
                 <strong><?php echo __($this->_getConfig('title_module')); ?></strong>
            </div>
        <?php } ?>

        <div class="block-content">
            <div id="<?php echo $tag_id; ?>" class="<?php /* @escapeNotVerified */
            echo $viewMode; ?> products-<?php /* @escapeNotVerified */
            echo $viewMode; ?>">

                <?php
                if ($this->_getConfig('product_source') == 'countdown_products') {
                    $dateTo = $this->_getConfig('date_to', '');
                    ?>
                    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
                        <div class="deals-time time-day">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-hours">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-mins">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-secs">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                    </div>
                <?php } ?>

                <?php $iterator = 1; ?>
                <div class="items product-items filterproducts">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product):
			
                        ?>
						
                        <div class="item product product-item" id="<?php echo $_product->getId();?>">
                            <div class="product-item-info" data-container="product-grid">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>

                                <?php // Product Image
                                ?>
                                <div class="image-product">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>

                                    <?= $_config->getLabelProduct($_product); ?>
                                </div>

                                <div class="product details product-item-details">
									 <div class="title-countdown-slider">
										 <h3 class="title-deals"><?php echo __('Limited-time offer! Sale end in:')?></h3>
										 <?php
										if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
											$specialToDate = $_product->getSpecialToDate();
											?>
											<div id="flipdown" class="flipdown <?php echo $tag_id;?>" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>"></div>
										<?php } ?>
									</div>
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */
										echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									</div>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?> 
                                    <?php
                                    
                                    /* @escapeNotVerified */
                                    echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <div class="product-item-inners">
                                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                            <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                          data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                          action="<?= /* @NoEscape */
                                                          $postParams['action'] ?>" method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?= /* @escapeNotVerified */
                                                               $postParams['data']['product'] ?>">
                                                        <input type="hidden" name="<?= /* @escapeNotVerified */
                                                        Action::PARAM_NAME_URL_ENCODED ?>"
                                                               value="<?= /* @escapeNotVerified */
                                                               $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */
                                                        __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->isAvailable()): ?>
                                                        <div class="stock available"><span><?= /* @escapeNotVerified */
                                                                __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                                __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <div data-role="add-to-links"
                                                 class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Compare') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>

                                   
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                
            </div>
        </div>
    </div>

   <script>
        require([
            'jquery','flipdown'
        ], function ($) {
            ;(function (el) {
                var $element = $(el);
                $(".flipdown.<?php echo $tag_id;?>", $element).each(function () {
                    var timer = $(this).data('timer');
                    var amount = new Date(timer).getTime() - new Date().getTime();
                    amount = Math.floor(amount / 1000);
                    days = Math.floor(amount / 86400);
                    var datetoday = (new Date().getTime() / 1000) + (86400 * days) + 1;
                    var flipdown = new FlipDown(datetoday).start();
                });
            })('#<?php echo $tag_id ?>');
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }



        </script>
    <?php endif; ?>
<?php endif; ?>
