<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<?php $inputClass = 'checkbox product bundle option bundle-option-' . $block->escapeHtmlAttr($_option->getId()) ?>
<?php $inputId = 'bundle-option-' . $block->escapeHtmlAttr($_option->getId()) ?>
<?php $inputName = 'bundle_option[' . $block->escapeHtmlAttr($_option->getId()) . ']' ?>
<?php $dataValidation = 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' .
    $block->escapeHtmlAttr($_option->getId()) . ']&quot;]:checked\'}"' ?>
<?php
$_config = $this->helper('Sm\BundleImage\Helper\Data');
?>

<div class="field option <?= ($_option->getRequired()) ? ' required' : '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @noEscape */
                $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <?= /* @noEscape */
                $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
                <?php
                $productLinkNested = $block->getProductLink($_selections[0]);
                $productIdNested   = $_selections[0]->getId();
                ?>
                <?php if ($productLinkNested) { ?>
                    <a class="view-detail" href="<?php echo $productLinkNested; ?>"
                       target="_blank"><?php echo __('View detail') ?></a>

                    <?php if ($_config->checkQuickView()) { ?>
                        <a class="action quickview-handler sm_quickview_handler"
                           href="<?php echo $this->getUrl('') . "cartquickpro/catalog_product/view/id/" . $productIdNested ?>">
                            <?php echo $_config->getQuickCartConfig('label_button') ?>
                        </a>
                    <?php } ?>

                <?php } ?>
                <input type="hidden"
                       class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                       name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                       value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
            <?php else: ?>
                <?php foreach ($_selections as $selection): ?>
                    <?php $sectionId = $selection->getSelectionId() ?>
                    <?php
                    $productLink = $block->getProductLink($selection);
                    $productId   = $selection->getId();
                    ?>
                    <div class="field choice choice-inline">
                        <input class="<?= /* @noEscape */
                        $inputClass ?> change-container-classname"
                               id="<?= /* @noEscape */
                               $inputId . '-' . $block->escapeHtmlAttr($sectionId) ?>"
                               type="checkbox"
                            <?php if ($_option->getRequired()): ?>
                                <?= /* @noEscape */
                                $dataValidation ?>
                            <?php endif; ?>
                               name="<?= /* @noEscape */
                               $inputName . '[' . $block->escapeHtmlAttr($sectionId) ?>]"
                               data-selector="<?= /* @noEscape */
                               $inputName . '[' . $block->escapeHtmlAttr($sectionId) ?>]"
                            <?php if ($block->isSelected($selection)): ?>
                                <?= ' checked="checked"' ?>
                            <?php endif; ?>
                            <?php if (!$selection->isSaleable()): ?>
                                <?= ' disabled="disabled"' ?>
                            <?php endif; ?>
                               value="<?= $block->escapeHtmlAttr($sectionId) ?>"
                               data-errors-message-box="#validation-message-box"/>
                        <div class="label-option-content">
                            <span class="label"
                                  for="<?= /* @noEscape */
                                  $inputId . '-' . $block->escapeHtmlAttr($sectionId) ?>">
                            <span><?= /* @noEscape */
                                $block->getSelectionQtyTitlePrice($selection) ?></span>
                            <br/>
                            <?= /* @noEscape */
                            $block->getTierPriceRenderer()->renderTierPrice($selection) ?>
                            </span>

                            <?php if ($productLink) { ?>
                                <a class="view-detail detail-btn" href="<?php echo $productLink; ?>"
                                   title="<?php echo __('View detail') ?>"
                                   target="_blank"><span><?php echo __('View detail') ?></span></a>

                                <?php if ($_config->checkQuickView()) { ?>
                                    <a class="action quickview-handler sm_quickview_handler quickview-btn"
                                       title="<?php echo $_config->getQuickCartConfig('label_button'); ?>"
                                       href="<?php echo $this->getUrl('') . "cartquickpro/catalog_product/view/id/" . $selection->getId() ?>">
                                        <span><?php echo $_config->getQuickCartConfig('label_button') ?></span>
                                    </a>
                                <?php } ?>
                            <?php } ?>
                        </div>

                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
                <div id="validation-message-box"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
