<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-39">
    <div class="header-content ontop-element">
		<div class="row align-items-center">
			<div class="col-md-2">
				 <div class="l-content">
					<div class="logo-container">
						<?php echo $this->getChildHtml("logo"); ?>
					</div>
				</div>
			</div>
			<div class="col-md-10">
				<div class="m-content">
					<div class="t-content">
						<div class="row">
							<div class="col-md-6">
								
								<div class="block-header store-setting">
									<div class="block-header-content language-currency">
										<?php echo $this->getChildHtml("store_language"); ?>
										<?php echo $this->getChildHtml("currency"); ?>
									</div>
								</div>
							</div>
							<div class="col-md-6">
								
								<div class="block-header customer-links" data-move="customer-mobile"> 
									<div class="block-header-content">
										<?php echo $this->getChildHtml("header.links"); ?>
									</div>
								</div>
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('location-link-header')->toHtml(); ?>
							</div>
						</div>
					</div>
					<div class="b-content">
					<div class="desktop-menu">
						<div class="vertical-block"> 
							<?php
							if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
								echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-vertical')->toHtml();
							} else {
								echo $this->getChildHtml("vertical-css"); 
							}
							?>
						</div>
					   <div class="horizontal-block">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?>
						</div>
					</div>
					<div class="r-content">
						<div class="block-header search-container">
							<div class="block-header-content">
								<?php echo $this->getChildHtml("topSearch"); ?>
							</div>
						</div>
						
						<div class="minicart-header" data-move="minicart-mobile">
							<?php echo $this->getChildHtml("minicart"); ?>
						</div>

					</div>
				</div>  
			</div>
			</div>
		</div>       		
    </div>
</div>
