<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-29">
    <div class="header-top">
        <div class="container">
            <div class="top-content clearfix">
                <div class="top-l">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social-block')->toHtml(); ?>
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-call-free')->toHtml(); ?>
                </div>

                <div class="top-r">
                    <div class="language-currency">
                        <?php echo $this->getChildHtml("store_language"); ?>
                        <?php echo $this->getChildHtml("currency"); ?>
                    </div>

                    <div class="header-block account-block">
                        <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo __('My Account') ?></a>

                        <div class="header-dropdown">
                            <div class="customer-links" data-move="customer-mobile">
                                <?php echo $this->getChildHtml("header.links"); ?>
                            </div>
                        </div>
                    </div>

                    <div class="minicart-header" data-move="minicart-mobile">
                        <?php echo $this->getChildHtml("minicart"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="hd-bottom-content clearfix">
                <div class="b-content">
                    <div class="logo-container">
                        <?php echo $this->getChildHtml("logo"); ?>
                    </div>

                    <div class="desktop-menu">
                        <?php
                        if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                        } else {
                            echo $this->getChildHtml("horizontal-css");
                        }
                        ?>
                    </div>

                    <div class="search-container">
                        <?php echo $this->getChildHtml("topSearch"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
