<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-35">

    <div class="header-top">
		<a class="btn-close icon-x" href="javascript:void(0)"><span class="hidden"></span></a>
        <div class="hd-top-content">
            <div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('saleoff-hd35')->toHtml(); ?>
					</div>

					<div class="col-lg-6">
						<div class="r-header">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-faqs-hd35')->toHtml(); ?>
							<div class="customer-header">
								<div class="language-currency">
									<?php echo $this->getChildHtml("store_language"); ?>
									<?php echo $this->getChildHtml("currency"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
	<div class="header-middle">

            <div class="container">
				<div class="row align-items-center">
					<div class="col-lg-5">
						 <div class="vertical-block">
							<?php
							if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
								echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-vertical')->toHtml();
							} else {
								echo $this->getChildHtml("vertical-css");
							}
							?>
						</div>
					</div>
					<div class="col-lg-2">
						<div class="logo">
							<div class="logo-container">
								<?php echo $this->getChildHtml("logo"); ?>
							</div>
						</div>
					</div>
					<div class="col-lg-5">
						<div class="r-header">

							<div class="customer-header">
								<div class="search-container">
									<a href="javascript:void(0)" class="icon-search1"><span class="hidden"></span></a>
									<?php echo $this->getChildHtml("topSearch"); ?>
								</div>

								<div class="header-block account-block">
									<a href="<?php echo $this->getUrl('customer/account') ?>"></a>

									<div class="header-dropdown">
										<div class="customer-links" data-move="customer-mobile">
											<?php echo $this->getChildHtml("header.links"); ?>
										</div>
									</div>
								</div>

								<?php echo $this->getChildHtml("wishlist.header"); ?>

								<div class="minicart-header" data-move="minicart-mobile">
									<?php echo $this->getChildHtml("minicart"); ?>
								</div>

							</div>
						</div>
					</div>
				</div>
            </div>



	</div>
    <div class="header-bottom">
        <div class="container">
            <div class="desktop-menu">
                <?php
                if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                } else {
                    echo $this->getChildHtml("horizontal-css");
                }
                ?>

                
            </div>
        </div>
    </div>
</div>
