<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$welcome = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('design/header/welcome');

?>

<div class="header-container header-style-37">
    <div class="header-top">
        <div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-header-text-1')->toHtml(); ?>
           
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="left-content">
                <div class="logo-container">
                    <?php echo $this->getChildHtml("logo"); ?>
                </div>
            </div>

            <div class="right-content"> 
                <div class="content">
					<?php 
						echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support-header-37')->toHtml(); 
					?>
                    <div class="search-container">
                        <?php echo $this->getChildHtml("topSearch"); ?>
                    </div>
					 <?php echo $this->getChildHtml("wishlist.header"); ?>
                    <div class="minicart-header" data-move="minicart-mobile">
                        <?php echo $this->getChildHtml("minicart"); ?>
                    </div>
                    <div class="header-block account-block">
                        <a href="<?php echo $this->getUrl('customer/account') ?>"><span class="hidden"><?php echo __('Account');?></span></a>

                        <div class="header-dropdown">
                            <div class="customer-links" data-move="customer-mobile">
                                    <?php echo $this->getChildHtml("header.links"); ?>
                            </div>
                        </div>
                    </div>
					
					<div class="block-header header-block  store-setting">
                        <div class="block-header-content header-dropdown language-currency">
                            <?php echo $this->getChildHtml("store_language"); ?>
                            <?php echo $this->getChildHtml("currency"); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="desktop-menu">

                <div class="horizontal-block">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?>
                </div>
                 <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social-block')->toHtml(); ?>
            </div>
        </div>
    </div>
</div>
