<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-27">
    <div class="header-top">
        <div class="container clearfix">
            <div class="logo-container">
                <?php echo $this->getChildHtml("logo"); ?>
            </div>

            <div class="r-top-content">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support-header-27')->toHtml(); ?>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="bottom-content clearfix">
                <div class="horizontal-block">
                    <?php
                    if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                    } else {
                        echo $this->getChildHtml("horizontal-css");
                    }
                    ?>
                </div>

                <div class="customer-actions">
                    <div class="search-container">
                        <?php echo $this->getChildHtml("topSearch"); ?>
                    </div>

                    <div class="customer-links" data-move="customer-mobile">
                        <a href="#">
                            <span><?php echo __('My Account') ?></span>
                        </a>

                        <?php echo $this->getChildHtml("header.links"); ?>
                    </div>

                    <div class="minicart-header" data-move="minicart-mobile">
                        <?php echo $this->getChildHtml("minicart"); ?>
                    </div>

                    <div class="setting-block">
                        <div class="header-dropdown">
                            <?php echo $this->getChildHtml("store_language"); ?>
                            <?php echo $this->getChildHtml("currency"); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="bottom-note">
        <div class="container">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('note-medicine')->toHtml(); ?>
        </div>
    </div>
</div>
