<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-28">
    <div class="header-top clearfix">
        <div class="container clearfix">
            <div class="header-top-l">
                <ul>
                    <li class="phone">
                        <a href="#">(+888) 9434 6000</a>
                    </li>

                    <li class="email">
                        <a href="#">market@support.com</a>
                    </li>
                </ul>
            </div>

            <div class="header-top-c">
                <div class="hd-top-note">
                    Extra 30% off, plus free shipping
                </div>
            </div>

            <div class="header-top-r">
                <div class="language-currency">
                    <?php echo $this->getChildHtml("store_language"); ?>
                    <?php echo $this->getChildHtml("currency"); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element clearfix">
        <div class="container clearfix">
            <div class="logo-container">
                <?php echo $this->getChildHtml("logo"); ?>
            </div>

            <div class="horizontal-block">
                <?php
                if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                } else {
                    echo $this->getChildHtml("horizontal-css");
                }
                ?>
            </div>

            <div class="customer-actions">
                <div class="search-container">
                    <?php echo $this->getChildHtml("topSearch"); ?>
                </div>

                <div class="customer-links" data-move="customer-mobile">
                    <a href="#">
                        <span><?php echo __('My Account') ?></span>
                    </a>

                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>

                <?php echo $this->getChildHtml("wishlist.header"); ?>

                <div class="minicart-header" data-move="minicart-mobile">
                    <?php echo $this->getChildHtml("minicart"); ?>
                </div>
            </div>
        </div>
    </div>
</div>
