<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-4">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="language-currency">
                        <?php echo $this->getChildHtml("store_language"); ?>
                        <?php echo $this->getChildHtml("currency"); ?>
                    </div>
                </div>

                <div class="col-lg-7">
                    <div class="header-top-right">
                        <div class="customer-links" data-move="customer-mobile">
                            <?php echo $this->getChildHtml("header.links"); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="left-content">
                <div class="logo-container">
                    <?php echo $this->getChildHtml("logo"); ?>
                </div>
            </div>

            <div class="right-content">
                <div class="content">
                    <div class="cms-header">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cms-header-2')->toHtml(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="desktop-menu">
                <div class="vertical-block">
                    <?php
                    if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-vertical')->toHtml();
                    } else {
                        echo $this->getChildHtml("vertical-css");
                    }
                    ?>
                </div>

                <div class="search-cart">
                    <div class="search-container">
                        <?php echo $this->getChildHtml("topSearch"); ?>
                    </div>

                    <div class="minicart-header" data-move="minicart-mobile">
                        <?php echo $this->getChildHtml("minicart"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
