<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-26">
    <div class="header-top">
        <div class="container clearfix">
            <div class="header-l">
                <div class="language-currency">
                    <?php echo $this->getChildHtml("store_language"); ?>
                    <?php echo $this->getChildHtml("currency"); ?>
                </div>
            </div>

            <div class="header-c">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-header-text')->toHtml(); ?>
            </div>

            <div class="header-r">
                <div class="customer-links" data-move="customer-mobile">
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom">
        <div class="container clearfix">
            <div class="logo-container">
                <?php echo $this->getChildHtml("logo"); ?>
            </div>

            <div class="horizontal-block">
                <?php
                if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                } else {
                    echo $this->getChildHtml("horizontal-css");
                }
                ?>
            </div>

            <div class="header-cus">
                <div class="cus-content">
                    <div class="search-container">
                        <?php echo $this->getChildHtml("topSearch"); ?>
                    </div>

                    <?php echo $this->getChildHtml("wishlist.header"); ?>

                    <div class="minicart-header" data-move="minicart-mobile">
                        <?php echo $this->getChildHtml("minicart"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
