<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-18">
    <div class="header-middle ontop-element">
        <div class="container">
            <div class="l-content">
                <div class="logo-container">
                    <?php echo $this->getChildHtml("logo"); ?>
                </div>
            </div>

            <div class="m-content">
                <div class="desktop-menu">
                    <div class="horizontal-block">
                        <?php
                        if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                        } else {
                            echo $this->getChildHtml("horizontal-css");
                        }
                        ?>
                    </div>
                </div>
            </div>

            <div class="r-content">
                <div class="content">
                    <div class="block-header search-container">
                        <div class="block-header-content">
                            <?php echo $this->getChildHtml("topSearch"); ?>
                        </div>
                    </div>

                    <div class="block-header customer-links" data-move="customer-mobile">
                        <div class="block-header-content">
                            <?php echo $this->getChildHtml("header.links"); ?>
                        </div>
                    </div>

                    <div class="minicart-header" data-move="minicart-mobile">
                        <?php echo $this->getChildHtml("minicart"); ?>
                    </div>

                    <div class="block-header store-setting">
                        <div class="block-header-content language-currency">
                            <?php echo $this->getChildHtml("store_language"); ?>
                            <?php echo $this->getChildHtml("currency"); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
