<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="display-popup" style="display:none;">
    <div id="newsletter-popup">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-popup-validate-detail">
            <div class="w-newsletter clearfix">
                <div class="newsletter-info">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-popup-description')->toHtml(); ?>

                    <div class="top-newsletter">SIGN UP</div>
                    <div class="bottom-newsletter">NEWSLETTER</div>
                    <p class="news-description">Subscribe to the Market mailing list to receive updates on new arrivals,
                        special offers and other discount information.</p>

                    <div class="form-newsletter-popup">
                        <div class="input-box">
                            <input name="email" type="email" id="newsletter-popup-input" class="input-text"
                                   onfocus="if(this.value=='<?php echo __("Your email address") ?>') this.value='';"
                                   onblur="if(this.value=='') this.value='<?php echo __("Your email address") ?>';"
                                   value="<?php echo __("Your email address") ?>"
                                   data-validate="{required:true, 'validate-email':true}"/>
                        </div>

                        <div class="action-newsletter">
                            <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                            echo __('Subscribe') ?>" type="submit">
										<span><?php /* @escapeNotVerified */
                                            echo __('Subscribe') ?></span>
                            </button>
                        </div>
                    </div>

                    <div class="subscribe-bottom">
                        <div id="uniform-dont-show-again" class="checker"><span><input id="dont-show-again"
                                                                                       type="checkbox"></span>
                        </div>
                        <label for="dont-show-again"><?php echo __('Don\'t show this popup again') ?></label>
                    </div>

                    <div class="social-popup">
                        <ul>
                            <li>
                                <a href="#">
                                    <span class="icon-facebook1"><span class="hidden">Facebook</span></span>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <span class="icon-twitter1"><span class="hidden">Twitter</span></span>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <span class="icon-pinterest"><span class="hidden">Pinterest</span></span>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <span class="icon-vimeo"><span class="hidden">Vimeo</span></span>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <span class="icon-youtube"><span class="hidden">Youtube</span></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
