<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass  = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';

if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base">'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
    <h2 class="title">
    <?= /* @noEscape */
    $titleHtml ?>
    </h2>
<?php endif; ?>
